### ISSUE TITLE
Name of the place ...

### ISSUE THREAD

**Issue by cesaregerbino** [mapillary/mapillary-chrome-extension#1]
Hi all, I think that could be useful and fine put the place and state name somewhere .... near the Mapillary logo? near the "Explore"?

Anyway ... it's fine!!

**Comment by nickplesha** [comment]
Thanks for the feedback! 

The only reason that feature didn't make it to the current version is that some images in Mapillary don't have a location name right now. There is a simple solution of using a reverse geocoding service to fetch the location names for the image coordinates. That data would be saved to the `data.json`.

The location could be show somewhere around the map in the right corner or maybe in the left corner since it is currently empty.

I'll look into a geocoding service that would fit our needs.

**Comment by cesaregerbino** [comment]
The simplest one I know that is free is OSM Nomitatim but there are
several others based on OSM and you can invoke it at run time ... bye!!
Il 30/Mag/2016 18:09, "Nikola Pleša" notifications@github.com ha scritto:

**Comment by nickplesha** [comment]
We've updated the extension to minimise the number of requests on each load so we won't be adding new scripts at this time. When the image location name data on the backend covers all of the images in the rotation, we'll add the name of the place in the chrome extension as well.
